apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: myregistrykey
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgAsw4mEbX8prBTA1wrP+MCCrND2ONqvfB9xfqlwuwAgAnhjx9X/JygcfqOCa1gr5YUWLNvbieXEt4nQqe9G3i4ig9SQuqaKQ7Xo4o4eV18nn9EgV9Yh+nju7fXWSU4nTMVsxk/jkehawJGBs7bAYHZCJn3aMWqtzlDGwxe3kraCUZ/NBJ0dQxlXj1eVo1Y2YSjw98VtI7/3er4+EDtekj+Tcxu+90s3ylYhManuyuRotwjklfTJjSImd6iBn3mNGQwxbIv+bBSkLrgnlGiMw9XLA85qlc69BvBTe38zJunq0q8O7YdsaZEYZzcU10Fxns2Ndihn3LJyyOcdUXpLFoopsVz+UchApoWLGUKCE3JTmiss+wcj61Vc9/q5MMct6YW+rolqhSQhWSYc6W2Io/JzVFHbOYD/o5gtM+9eiac5GEJ2fILms9wF5bCUrtzmamc7VGYPBJwNR8lN/yyh2HvTPRcnOGtVfqrVu27bbH/DXJRNJhwTy0MP8s56S4DsesFurMghmV1D8TqxbG53seFB1gZnUAY/VC8+Bojqob44EdnltIzsnPtajn5fkejXpMYWw0oD4eS9zM+uY+xa7sQIijO2hlxVKUa3xPdB2U2rBhXMD+GACtMLs7CSdHmkzQi1oIJ52fKA2WR7HFuxe8W+KPw/FLBesrrythT5rJVkgDDKW27GsEwDLzeMAHQ6jxNaibS+SWP5luSrSeRHXbOBnOFxNzJDf/v4hOXP4cNTdJPaOYpqcqvRCL95v1c/0+06UsRzbcG6QEg2Hlpgywwvej3OYwsRtdZ4OvZMF9F2bsMUCtBHN7/fGbcgkGsNv2f61XJ+Jg3yikXjjWDqDzPAqD79ThHojkL3J/r27L3+LJ1fVVLiq8Cn3zgwIjTH4aggp1M0ummjpske+xoHlzm/Eg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: myregistrykey
      namespace: default
    type: kubernetes.io/dockerconfigjson

