apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-secret
  namespace: default
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgBHpJ2i2ZQlkYO1NQ0UMOIUV5hAYl/+C5dVgpB6Msv1Ob2/3SXglYWWoNg4yAbR6tBHvCjEy9MKKA+Ex27m7LzS9Uic5r/sel8pPvFYnFzv6CweYxpfe3JItOQfJbF5nPqGkVHqF9mAvnIyPok1l7i+GXv25Ql1xAEaVQ8geqybll1cXhmmERFerpCrbnxXDUHjCaqgXsyIHD8p0lCljxYC+Z1fqMX82GurdrpCBAQ/75acrX3Biz9KlbzAIHAXRnMPd2Fsb9ErsdEjhbKat6jtIBpq/il2/wYa+1yaLu8X5+hXQEvPd0rvvapPDj/PhNy9hI2aEd9QfADeqvV+EGZMJTxZ0ieuSdwDe+eaPiIj4waEFX8WQUp5QHPzX5YFba+7u24wBVrkLCthREVU51QzIVsjToMcIoMT5A2CK0X1JHglzKlGKi+FUCBOe+kN1ZHvoO7HJkZ8o82tLwV9cnUd87/pjkj7rzeC5PEqZJmg389QVzenoubNAewvDI3W6bIM+5yfa4HvzEzr0bNpQi86iXljvKu4u3qyu+K0ht2eFrncMroxaAo7OsjtXmmkZQua9Ha2nZf2ukWrdCmge27p1YWhyMuLMXuFzfSfcSZwP8axXDxHupCtzoItDclW2Wg8mxx0F+aPC4payifVbSo4UJWwyQb1UQjHBkvN946dw2F7ki5NiEY6Vcq1KtimoEC4QGQ=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysql-secret
      namespace: default
    type: Opaque

