apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
  namespace: default
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJhbGlhMTUzIiwicGFzc3dvcmQiOiJhbGk2OTEzMDIxYWEiLCJlbWFpbCI6ImFsaWFiZHJhYnU3OEBnbWFpbC5jb20iLCJhdXRoIjoiWVd4cFlURTFNenBoYkdrMk9URXpNREl4WVdFPSJ9fX0=
type: kubernetes.io/dockerconfigjson